name: basil_arcana
publish_to: 'none'
description: Basil's Arcana
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  share_plus: ^10.0.2
  uuid: ^4.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/data/cards_major_en.json
    - assets/data/spreads_en.json
