name: basil_arcana
publish_to: 'none'
description: Basil's Arcana
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  video_player: ^2.9.2
  video_player_web: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/deck/
    - assets/data/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: assets/icon/app_icon.png
